{% set name = "dvc-ssh" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bc082e04b99542cff0a48b22ec7ad6f6ecc2a11e65f84463b84c789c2beae97a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >={{ python_min }}
    - dvc
    - sshfs >=2021.11.2

test:
  imports:
    - dvc_ssh
  requires:
    - git
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - dvc version
    - dvc version | grep ssh

about:
  home: https://github.com/iterative/dvc-ssh
  summary: SSH plugin for DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
